# Generated by Django 2.2.7 on 2019-11-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pics')),
                ('discription', models.TextField()),
                ('designation', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
